import { StyleSheet } from 'react-native';
import { widthPercentageToDP as wp, heightPercentageToDP as hp } from "react-native-responsive-screen";
import { colors } from "@constants/themes";

export default StyleSheet.create({
    container: {
        flex: 1,
    },
    header: {
        flexDirection: "row",
        alignItems: "center",
        width: "100%",
        height: 35,
        padding: 2,
    },
    searchBar: {
        flexDirection: "row",
        alignItems: "center",
        width: wp("100%") - 90,
        height: 30,
        padding: 2,
        borderWidth: 0,
        borderRadius: 5,
        backgroundColor: colors.GREY.SECONDARY
    },
    searchIcon: {
        justifyContent: "center",
        alignItems: "center",
        width: 26,
        height: 26,
        backgroundColor: colors.WHITE,
        borderRadius: 5,
    },
    inputContainerStyle: {
        height: 30,
        borderBottomWidth: 0,
    },
    textInputStyle: {
        height: 30,
        width: wp("100%") - 120,
    },
    inputTextStyle: {
        height: 30,
        fontSize: 14,
    },
    listButton: {
        justifyContent: "center",
        alignItems: "center",
        marginLeft: 10,
        width: 50,
        height: 30,
        borderWidth: 0,
        borderRadius: 5,
        backgroundColor: colors.GREY.PRIMARY,
    },
    statusBar: {
        flexDirection: "row",
        alignItems: "center",
        width: wp("100%"),
        height: 40,
        padding: 10,
        backgroundColor: colors.GREY.SECONDARY,
    },
    greenButton: {
        justifyContent: "center",
        alignItems: "center",
        width: 80,
        height: 20,
        borderRadius: 5,
        backgroundColor: colors.GREEN.PRIMARY,
    },
    blueButton: {
        justifyContent: "center",
        alignItems: "center",
        width: 80,
        height: 20,
        borderRadius: 5,
        backgroundColor: '#4E9EE9',
    },
    orangeButton: {
        justifyContent: "center",
        alignItems: "center",
        width: 70,
        height: 20,
        borderRadius: 5,
        backgroundColor: '#FF9900',
    },
    whiteButton: {
        justifyContent: "center",
        alignItems: "center",
        width: 80,
        height: 20,
        borderRadius: 5,
        borderWidth: 0.5,
        backgroundColor: colors.WHITE,
    },
    redButton: {
        justifyContent: "center",
        alignItems: "center",
        width: 70,
        height: 20,
        borderRadius: 5,
        backgroundColor: colors.RED.PRIMARY,
    },
    white2Button: {
        justifyContent: "center",
        alignItems: "center",
        width: 70,
        height: 20,
        borderRadius: 5,
        borderWidth: 0.5,
        backgroundColor: colors.WHITE,
    },
    sort: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        width: 85,
        height: 20,
        paddingLeft: 5,
        paddingRight: 5,
        borderWidth: 0.5,
        borderRadius: 5,
        backgroundColor: colors.WHITE,
    },
    filters: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        width: 90,
        height: 20,
        paddingLeft: 5,
        paddingRight: 5,
        borderWidth: 0.5,
        borderRadius: 5,
        backgroundColor: colors.WHITE,
    },
    badge: {
        backgroundColor: colors.RED.PRIMARY,
        borderRadius: 7,
        width: 14,
        height: 14,
        justifyContent: "center",
        alignItems: "center",
    },
    badgeText: {
        color: "white",
        fontSize: 10,
        fontWeight: "bold",
    },
    save: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        width: 100,
        height: 20,
        paddingLeft: 5,
        paddingRight: 5,
        borderWidth: 0.5,
        borderRadius: 5,
        backgroundColor: colors.WHITE,
    },
    touch: {
        width: "100%",
        height: "100%",
        justifyContent: "center",
        alignItems: "center",
    },
    locationButton: {
        position: "absolute",
        bottom: 60,
        right: 20,
        justifyContent: "center",
        alignItems: "center",
        width: 30,
        height: 30,
        backgroundColor: colors.WHITE,
        borderRadius: 15,
        shadowColor: colors.BLACK,
        shadowOffset: { width: 2, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 1,
        elevation: 1,
    },
    drawView: {
        position: "absolute",
        top: 140,
        right: 20,
        flexDirection: 'row',
        justifyContent: "center",
        alignItems: "center",
    },
    drawButton: {
        flexDirection: 'row',
        justifyContent: "space-between",
        alignItems: "center",
        width: 100,
        height: 25,
        padding: 5,
        backgroundColor: colors.WHITE,
        borderRadius: 5,
        borderWidth: 0.5,
        shadowColor: colors.BLACK,
        shadowOffset: { width: 2, height: 2 },
        shadowOpacity: 0.5,
        shadowRadius: 1,
        elevation: 1,
    },
    applyButton: {
        flexDirection: 'row',
        justifyContent: "space-between",
        alignItems: "center",
        paddingLeft: 5,
        paddingRight: 5,
        paddingTop: 3,
        paddingBottom: 3,
        backgroundColor: colors.WHITE,
        borderRadius: 5,
        borderWidth: 0.9,
        borderColor: '#45AB62',
        shadowColor: colors.BLACK,
        shadowOffset: { width: 2, height: 2 },
        shadowOpacity: 0.5,
        shadowRadius: 1,
        elevation: 1,
    },
    cancelButton: {
        flexDirection: 'row',
        justifyContent: "space-between",
        alignItems: "center",
        paddingLeft: 5,
        paddingRight: 5,
        paddingTop: 3,
        paddingBottom: 3,
        backgroundColor: colors.WHITE,
        borderRadius: 5,
        borderWidth: 0.9,
        borderColor: '#EA4A4A',
        shadowColor: colors.BLACK,
        shadowOffset: { width: 2, height: 2 },
        shadowOpacity: 0.5,
        shadowRadius: 1,
        elevation: 1,
    },
    satButton: {
        position: "absolute",
        bottom: 20,
        right: 20,
        justifyContent: "center",
        alignItems: "center",
        width: 30,
        height: 30,
        backgroundColor: colors.WHITE,
        borderRadius: 15,
        shadowColor: colors.BLACK,
        shadowOffset: { width: 2, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 1,
        elevation: 1,
    },
    viewButton: {
        position: "absolute",
        bottom: 20,
        left: wp('100%') / 2 - 80,
        justifyContent: "center",
        alignItems: "center",
        width: 160,
        height: 25,
        borderRadius: 5,
        shadowColor: colors.BLACK,
        shadowOffset: { width: 1, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 1,
        elevation: 1,
    },
    customMarker: {
        justifyContent: 'center',
        alignItems: 'center',
        paddingLeft: 5,
        paddingRight: 5,
        height: 20,
        borderRadius: 4,
        borderWidth: 2
    },
    triangle: {
        transform: [
            { rotate: '180deg' }
        ],
        width: 0,
        height: 0,
        backgroundColor: 'transparent',
        borderStyle: 'solid',
        borderLeftWidth: 6,
        borderRightWidth: 6,
        borderBottomWidth: 6,
        borderLeftColor: 'transparent',
        borderRightColor: 'transparent',
        borderBottomColor: '#549E65'
    },
    clusterMarker: {
        justifyContent: "center",
        alignItems: "center",
    },
    polygonMarker: {
        width: 20,
        height: 20,
        backgroundColor: colors.BLUE.PRIMARY,
        borderColor: colors.WHITE,
        borderWidth: 3,
        shadowColor: colors.BLACK,
        shadowOffset: { width: 1, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 1,
        elevation: 1,
    },
    loading: {
        justifyContent: 'center',
        alignItems: 'center',
        marginLeft: wp('50%') - 20,
        marginBottom: 10,
        width: 40,
        height: 40,
        borderRadius: 5,
        backgroundColor: '#00000080',
        shadowColor: colors.BLACK,
        shadowOffset: { width: 1, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 1,
        elevation: 1,
    }
});